name: Android Build

on: 
  push: 
    branches: [ master ]
  pull_request_target:
    branches: [ master ]

    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#  we want to check out our project.    
      - name: Checkout
        uses: actions/checkout@v2.3.4
# setup our project with java 1.8        
      - name: Set up our JDK environment
        uses: actions/setup-java@v1.4.3
        with:
            java-version: 1.8
# Check Linter
      - name: Run Kotlin Linter
        run: ./gradlew lint
# Build with Gradle
      - name: Build with Gradle
        run: ./gradlew build 
# Make artifact APK 
      - name: Upload APK
        uses: actions/upload-artifact@v2.2.3
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
 